[package]
name = "rustbucket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
ctrlc = "3.4"
fs2 = "0.4"
nix = { version = "0.27", features = ["process"] }
memmap2 = "0.9"
threadpool = "1.8" 